config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :chatrooms do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :comments
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chatroom
  broadcasts_to :chatroom
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def create
    @chatroom = Chatroom.create(chatroom_params)
    if @chatroom.save
      redirect_to root_path, notice: "Chatroom created!"
    else
      redirect_to root_path, notice: "Chatroom names can't be blank."
    end
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @comment = Comment.new
    @comments = @chatroom.comments
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @comment = @chatroom.comments.create(comment_params)
    if @comment.save
      handle_response(@chatroom)
    else
      redirect_to chatroom_path(@chatroom), notice: "Comments can't be blank."
    end
  end

  def edit
    @comment = current_comment
  end

  def update
    @comment = current_comment
    @comment.update(comment_params)
    handle_response(@comment.chatroom)
  end

  def destroy
    @comment = current_comment
    @chatroom = @comment.chatroom
    @comment.destroy
    handle_response(@chatroom)
  end

  private

  def current_comment
    @current_comment ||= Comment.find(params[:id])
  end

  def handle_response(chatroom)
    respond_to do |format|
      format.html { redirect_to chatroom_path(chatroom) }
      Turbo::StreamsChannel.broadcast_update_to(
        "chatroom_channel_#{chatroom.id}",
        partial: "chatrooms/comments",
        target: "target",
        locals: {comments: chatroom.comments}
      )
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @chatrooms = Chatroom.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chatrooms/_comments.html.erb
<div id="target">
  <% comments.each do |comment| %>
    <%= turbo_frame_tag comment do %>
      <h3>
        <%= comment.content %>
        <%= link_to "Edit", edit_comment_path(comment) %>
        <%= "|" %>
        <%= link_to "Delete", comment_path(comment), data: { "turbo-method": :delete } %>
      </h3>
    <% end %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<%= turbo_stream_from "chatroom_channel_#{@chatroom.id}" %>

<h1><%= @chatroom.name %></h1>

<h2>Add a comment</h2>
<%= simple_form_for @comment, url: chatroom_comments_path(@chatroom) do |f| %>
  <h4><%= f.input :content %></h4>
  <%= f.button :submit %>
<% end %>

<%= render partial: "layouts/flash", locals: {desired_message: "Comments can't be blank."} %>

<%= render partial: "comments", locals: {comments: @comments} %>

app/views/comments/edit.erb
<%= turbo_frame_tag @comment do %>
  <h2>Edit this comment</h2>
  <%= simple_form_for @comment, url: comment_path(@comment) do |f| %>
    <h4><%= f.input :content %></h4>
    <%= f.button :submit %>
  <% end %>
  <%= link_to "Back", chatroom_path(@comment.chatroom) %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <% if message == desired_message %>
    <h2 class="flash__message">
      <%= message %>
    </h2>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render partial: "layouts/flash", locals: {desired_message: "Chatroom created!"} %>

<h1>Home page</h1>

<h2><%= link_to "Turbo tutorial", "https://www.hotrails.dev/turbo-rails/turbo-frames-and-turbo-streams" %></h2>

<%= simple_form_for Chatroom.new, url: chatrooms_path do |f| %>
  <h4><%= f.input :name %></h4>
  <%= f.button :submit %>
<% end %>

<%= render partial: "layouts/flash", locals: {desired_message: "Chatroom names can't be blank."} %>

<br/>

<% @chatrooms.each do |chatroom| %>
  <h3><%= link_to chatroom.name, chatroom_path(chatroom) %></h3>
<% end %>